version: "3.3"

services:
  app:
    container_name: cuha-homepage
    image: openjdk:21
    volumes:
      - ./build/libs:/root
    ports:
      - "10001:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cuha
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=cuhazngk
    command: sh -c "sleep 10; java -jar /root/app.jar"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: cuha-mysql
    image: mysql:8.0.37
    user: "1000:1000"
    environment:
      MYSQL_ROOT_PASSWORD: cuhazngk
      MYSQL_DATABASE: cuha
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
      INNODB_FORCE_RECOVERY: 1
    volumes:
      - ./mysql-data:/var/lib/mysql
      # - ./mysql-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"  # 외부에서 MySQL 접근 가능
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
